/**
 * 身份持久化模块
 * 管理SOUL快照和版本历史
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { SOULSnapshot, SOULConfig, EvolutionRecord } from './types';

export class IdentityPersistence {
  private config: SOULConfig;
  private snapshotDir: string;
  private historyFile: string;

  constructor(config: SOULConfig) {
    this.config = config;
    this.snapshotDir = path.join(config.dataPath, 'snapshots');
    this.historyFile = path.join(config.dataPath, 'evolution-history.json');
    this.ensureDirectories();
  }

  private async ensureDirectories(): Promise<void> {
    try {
      await fs.mkdir(this.snapshotDir, { recursive: true });
    } catch (error) {
      // 目录可能已存在，忽略错误
    }
  }

  async saveSnapshot(snapshot: SOULSnapshot, description?: string): Promise<void> {
    await this.ensureDirectories();

    const snapshotFile = path.join(this.snapshotDir, `${snapshot.id}.json`);
    const dataToSave = {
      ...snapshot,
      description: description || 'Automatic snapshot'
    };

    await fs.writeFile(snapshotFile, JSON.stringify(dataToSave, null, 2), 'utf8');

    // 同时保存为 SOUL.md 格式
    await this.saveSoulMarkdown(snapshot, description);

    // 清理旧快照
    await this.cleanupOldSnapshots();
  }

  private async saveSoulMarkdown(snapshot: SOULSnapshot, description?: string): Promise<void> {
    const mdPath = path.join(this.config.dataPath, 'SOUL.md');

    const mdContent = `# SOUL Identity Document

## Basic Information
- **Version**: \`${snapshot.version}\`
- **Snapshot ID**: \`${snapshot.id}\`
- **Timestamp**: ${snapshot.timestamp.toISOString()}
- **Checksum**: \`${snapshot.checksum}\`
- **Description**: ${description || 'Automatic snapshot'}

---

## Personality Profile

### Identity
- **Name**: ${snapshot.personality.name}
- **Nickname**: ${snapshot.personality.nickname}
- **Temperament**: ${snapshot.personality.temperament}

### Speaking Style
| Trait | Level (0-10) |
|-------|-------------|
| Formality | ${snapshot.personality.speakingStyle.formality} |
| Enthusiasm | ${snapshot.personality.speakingStyle.enthusiasm} |
| Humor | ${snapshot.personality.speakingStyle.humor} |
| Empathy | ${snapshot.personality.speakingStyle.empathy} |
| Directness | ${snapshot.personality.speakingStyle.directness} |

### Catchphrases
${snapshot.personality.catchphrases.map(p => `- "${p}"`).join('\n')}

---

## Core Values

### Priorities
${snapshot.values.priorities.map(v => `- ${v}`).join('\n')}

### Boundaries
${snapshot.values.boundaries.map(v => `- ${v}`).join('\n')}

### Ethical Principles
${snapshot.values.ethicalPrinciples.map(v => `- ${v}`).join('\n')}

### Behavioral Guidelines
${snapshot.values.behavioralGuidelines.map(v => `- ${v}`).join('\n')}

---

## Current Emotional State
- **Mood**: ${snapshot.emotionState.mood}
- **Energy**: ${snapshot.emotionState.energy}/10
- **Focus**: ${snapshot.emotionState.focus}/10
- **Stress**: ${snapshot.emotionState.stress}/10

---

## Relationship Summary
- **Total Relationships**: ${Object.keys(snapshot.relationships).length}

---

*This document was auto-generated by SelfClaw SOUL Module*
*DO NOT EDIT MANUALLY - Use the management interface to update*
`;

    await fs.writeFile(mdPath, mdContent, 'utf8');
  }

  async loadSnapshot(snapshotId: string): Promise<SOULSnapshot | null> {
    try {
      const snapshotFile = path.join(this.snapshotDir, `${snapshotId}.json`);
      const content = await fs.readFile(snapshotFile, 'utf8');
      const data = JSON.parse(content);

      return {
        ...data,
        timestamp: new Date(data.timestamp),
        emotionState: {
          ...data.emotionState,
          lastUpdated: new Date(data.emotionState.lastUpdated)
        }
      };
    } catch (error) {
      return null;
    }
  }

  async loadLatest(): Promise<SOULSnapshot | null> {
    try {
      const files = await fs.readdir(this.snapshotDir);
      const jsonFiles = files.filter(f => f.endsWith('.json'));

      if (jsonFiles.length === 0) {
        return null;
      }

      // 按创建时间排序，获取最新的
      let latest: SOULSnapshot | null = null;
      let latestTime = 0;

      for (const file of jsonFiles) {
        try {
          const content = await fs.readFile(path.join(this.snapshotDir, file), 'utf8');
          const snapshot = JSON.parse(content);
          const time = new Date(snapshot.timestamp).getTime();

          if (time > latestTime) {
            latestTime = time;
            latest = {
              ...snapshot,
              timestamp: new Date(snapshot.timestamp),
              emotionState: {
                ...snapshot.emotionState,
                lastUpdated: new Date(snapshot.emotionState.lastUpdated)
              }
            };
          }
        } catch (e) {
          // 跳过损坏的文件
          continue;
        }
      }

      return latest;
    } catch (error) {
      return null;
    }
  }

  async listSnapshots(limit?: number): Promise<Array<{
    id: string;
    timestamp: Date;
    version: string;
    description?: string;
  }>> {
    try {
      const files = await fs.readdir(this.snapshotDir);
      const jsonFiles = files.filter(f => f.endsWith('.json'));

      const snapshots: any[] = [];

      for (const file of jsonFiles) {
        try {
          const content = await fs.readFile(path.join(this.snapshotDir, file), 'utf8');
          const data = JSON.parse(content);
          snapshots.push({
            id: data.id,
            timestamp: new Date(data.timestamp),
            version: data.version,
            description: data.description
          });
        } catch (e) {
          continue;
        }
      }

      snapshots.sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());

      return limit ? snapshots.slice(0, limit) : snapshots;
    } catch (error) {
      return [];
    }
  }

  private async cleanupOldSnapshots(): Promise<void> {
    const snapshots = await this.listSnapshots();

    if (snapshots.length > this.config.maxSnapshots) {
      const toDelete = snapshots.slice(this.config.maxSnapshots);
      for (const snapshot of toDelete) {
        try {
          const snapshotFile = path.join(this.snapshotDir, `${snapshot.id}.json`);
          await fs.unlink(snapshotFile);
        } catch (e) {
          // 忽略删除错误
        }
      }
    }
  }

  async deleteSnapshot(snapshotId: string): Promise<boolean> {
    try {
      const snapshotFile = path.join(this.snapshotDir, `${snapshotId}.json`);
      await fs.unlink(snapshotFile);
      return true;
    } catch (error) {
      return false;
    }
  }

  async saveEvolutionHistory(history: EvolutionRecord[]): Promise<void> {
    await this.ensureDirectories();
    await fs.writeFile(this.historyFile, JSON.stringify(history, null, 2), 'utf8');
  }

  async loadEvolutionHistory(): Promise<EvolutionRecord[]> {
    try {
      const content = await fs.readFile(this.historyFile, 'utf8');
      const data = JSON.parse(content);
      return data.map((r: any) => ({
        ...r,
        timestamp: new Date(r.timestamp)
      }));
    } catch (error) {
      return [];
    }
  }

  async appendEvolutionRecord(record: EvolutionRecord): Promise<void> {
    const history = await this.loadEvolutionHistory();
    history.push(record);
    await this.saveEvolutionHistory(history);
  }

  async exportFullBackup(backupPath: string): Promise<void> {
    const latest = await this.loadLatest();
    const history = await this.loadEvolutionHistory();
    const snapshots = await this.listSnapshots();

    const backup = {
      exportedAt: new Date().toISOString(),
      latestSnapshot: latest,
      evolutionHistory: history,
      allSnapshots: snapshots
    };

    await fs.writeFile(backupPath, JSON.stringify(backup, null, 2), 'utf8');
  }

  async importBackup(backupPath: string): Promise<boolean> {
    try {
      const content = await fs.readFile(backupPath, 'utf8');
      const backup = JSON.parse(content);

      if (backup.latestSnapshot) {
        await this.saveSnapshot(backup.latestSnapshot, 'Restored from backup');
      }

      if (backup.evolutionHistory) {
        await this.saveEvolutionHistory(backup.evolutionHistory);
      }

      return true;
    } catch (error) {
      return false;
    }
  }

  getDataPath(): string {
    return this.config.dataPath;
  }

  getSnapshotPath(snapshotId: string): string {
    return path.join(this.snapshotDir, `${snapshotId}.json`);
  }
}
