/**
 * SelfClaw 李诞七步写作框架
 * 帮助将复杂概念写得深入浅出，让人愿意看、看得懂、愿意信
 * 基于李诞口述教学的七步写作法
 */

class LiDanWritingFramework {
  constructor() {
    this.steps = [
      { id: 1, name: '开场故事', description: '用一个真实的故事开场，抓住读者注意力' },
      { id: 2, name: '错误答案', description: '先讲大多数人会犯的错误，建立共鸣' },
      { id: 3, name: '正确答案', description: '给出你的核心观点/解决方案' },
      { id: 4, name: '触类旁通', description: '用其他领域的例子来佐证观点' },
      { id: 5, name: '对比冲击', description: '通过对比制造认知冲击' },
      { id: 6, name: '结尾升华', description: '拔高立意，留下余味' },
      { id: 7, name: '延伸阅读', description: '给出进阶学习的方向' }
    ];
    
    this.templates = this.loadTemplates();
  }

  /**
   * 加载各步骤的模板
   */
  loadTemplates() {
    return {
      openingStory: {
        types: ['个人经历', '新闻事件', '历史典故', '客户案例', '反常识现象'],
        template: '你知道吗？最近发生了一件事...'
      },
      wrongAnswer: {
        angles: ['认知误区', '普遍偏见', '惯性思维', '传统做法'],
        template: '大多数人以为...但其实这是错的，因为...'
      },
      correctAnswer: {
        structures: ['定义+举例', '原理+应用', '步骤+说明'],
        template: '正确的做法其实是...核心原理是...'
      },
      analogy: {
        domains: ['生物学', '物理学', '经济学', '心理学', '历史'],
        template: '这就像...领域的...原理一样...'
      },
      contrast: {
        pairs: ['理想vs现实', '过去vs现在', '表面vs本质', '理论vs实践'],
        template: '而当你...的时候，你会发现...与...完全不同...'
      },
      elevation: {
        levels: ['个人成长', '团队组织', '行业趋势', '社会价值'],
        template: '从更深层次来看，这其实意味着...'
      },
      furtherReading: {
        formats: ['推荐书籍', '推荐文章', '推荐课程', '实践练习'],
        template: '如果你想深入了解，可以看看...'
      }
    };
  }

  /**
   * 生成完整的七步写作大纲
   */
  generateOutline(topic, options = {}) {
    console.log(`📝 为「${topic}」生成七步写作框架...`);
    
    const outline = {
      topic,
      meta: {
        generatedAt: new Date().toISOString(),
        tone: options.tone || 'professional',
        audience: options.audience || 'general'
      },
      steps: []
    };

    // 步骤1: 开场故事
    outline.steps.push({
      step: 1,
      name: '开场故事',
      prompt: `为「${topic}」写一个吸引人的开场故事。可以用个人经历、新闻事件或反常识现象开头，100字左右。`,
      checklist: [
        '有具体场景和人物吗？',
        '有冲突或悬念吗？',
        '能引起读者好奇吗？'
      ]
    });

    // 步骤2: 错误答案
    outline.steps.push({
      step: 2,
      name: '错误答案',
      prompt: `关于「${topic}」，大多数人有什么错误的认知或做法？列举2-3个常见误区，并说明为什么是错的。`,
      checklist: [
        '是真正普遍的误区吗？',
        '解释清楚错在哪里了吗？',
        '和后面的正确答案形成对比了吗？'
      ]
    });

    // 步骤3: 正确答案
    outline.steps.push({
      step: 3,
      name: '正确答案',
      prompt: `给出「${topic}」的核心观点/解决方案。用清晰的结构阐述，配上1-2个具体例子。`,
      checklist: [
        '观点清晰明确吗？',
        '有具体例子支撑吗？',
        '逻辑通顺吗？'
      ]
    });

    // 步骤4: 触类旁通
    outline.steps.push({
      step: 4,
      name: '触类旁通',
      prompt: `用其他领域的例子来佐证「${topic}」的观点。比如用生物学、物理学、经济学、心理学或历史中的现象来类比。`,
      checklist: [
        '类比恰当吗？',
        '能帮助理解吗？',
        '跨领域了吗？'
      ]
    });

    // 步骤5: 对比冲击
    outline.steps.push({
      step: 5,
      name: '对比冲击',
      prompt: `通过对比制造认知冲击。可以是理想vs现实、过去vs现在、表面vs本质、理论vs实践等维度。`,
      checklist: [
        '对比强烈吗？',
        '有冲击力吗？',
        '加深理解了吗？'
      ]
    });

    // 步骤6: 结尾升华
    outline.steps.push({
      step: 6,
      name: '结尾升华',
      prompt: `拔高「${topic}」的立意。从个人成长、团队组织、行业趋势或社会价值等更高维度来收尾，留下余味。`,
      checklist: [
        '立意拔高了吗？',
        '不空洞吗？',
        '能引发思考吗？'
      ]
    });

    // 步骤7: 延伸阅读
    outline.steps.push({
      step: 7,
      name: '延伸阅读',
      prompt: `给出「${topic}」的进阶学习方向。可以是推荐书籍、文章、课程，或者给读者留一个实践练习。`,
      checklist: [
        '有具体推荐吗？',
        '有实践指导吗？',
        '方向清晰吗？'
      ]
    });

    return outline;
  }

  /**
   * 根据框架生成完整文章初稿
   */
  async generateDraft(topic, contentByStep) {
    console.log(`✍️ 生成「${topic}」文章初稿...`);

    let draft = `# ${topic}\n\n`;
    draft += `> 本文基于李诞七步写作框架创作\n\n`;
    draft += `---\n\n`;

    for (let i = 0; i < 7; i++) {
      const stepName = this.steps[i].name;
      const content = contentByStep[i] || `[待补充：${stepName}]`;
      
      if (i === 0) {
        draft += `## 👉 故事从这里开始\n\n`;
      } else {
        draft += `## ${i + 1}. ${stepName}\n\n`;
      }
      
      draft += content + '\n\n';
      
      // 步骤间的过渡语
      if (i < 6) {
        const transitions = [
          '听到这里，你可能会想...',
          '但问题来了...',
          '别急，让我们继续深入...',
          '这还没完，还有更重要的...',
          '但真正的核心在于...',
          '最后，让我们站得更高一点看...'
        ];
        draft += `> ${transitions[i]}\n\n`;
      }
    }

    draft += `---\n\n`;
    draft += `*Generated by SelfClaw LiDan Writing Framework* 📝\n`;

    return draft;
  }

  /**
   * 检查文章是否符合七步框架标准
   */
  auditArticle(article) {
    const auditResult = {
      score: 0,
      checks: [],
      suggestions: []
    };

    const stepChecks = [
      { keyword: '故事', name: '开场故事', weight: 15 },
      { keyword: ['误区', '错误', '不对'], name: '错误答案', weight: 15 },
      { keyword: ['正确', '核心', '本质'], name: '正确答案', weight: 20 },
      { keyword: ['就像', '比如', '例如'], name: '触类旁通', weight: 10 },
      { keyword: ['对比', '相比', 'vs'], name: '对比冲击', weight: 10 },
      { keyword: ['其实', '本质', '更深'], name: '结尾升华', weight: 15 },
      { keyword: ['推荐', '建议', '练习'], name: '延伸阅读', weight: 15 }
    ];

    stepChecks.forEach(check => {
      const keywords = Array.isArray(check.keyword) ? check.keyword : [check.keyword];
      const found = keywords.some(kw => article.includes(kw));
      
      auditResult.checks.push({
        step: check.name,
        passed: found,
        weight: check.weight
      });
      
      if (found) {
        auditResult.score += check.weight;
      } else {
        auditResult.suggestions.push(`建议在「${check.name}」部分加强，可以添加包含 ${keywords.join('/')} 的内容`);
      }
    });

    return auditResult;
  }

  /**
   * 获取写作金句
   */
  getQuotes() {
    return [
      '好的写作不是写漂亮话，而是让读者觉得你懂他。',
      '先让人愿意看，再让人看得懂，最后让人愿意信。',
      '故事是糖，包着你想讲的道理那个药。',
      '不要直接给答案，先让读者意识到自己的问题。',
      '写文章就是和读者聊天，别端着。',
      '把复杂的事情说简单，是一种能力。',
      '结尾要像余音绕梁，让人走了还在想。'
    ];
  }
}

module.exports = LiDanWritingFramework;
